
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LTAG RTAG TEXTdocument : elementoselementos : elemento elementos\n| elementoelemento : LTAG TEXT RTAG\n| LTAG elementos RTAG'
    
_lr_action_items = {'LTAG':([0,3,4,8,9,],[4,4,4,-4,-5,]),'$end':([1,2,3,5,8,9,],[0,-1,-3,-2,-4,-5,]),'RTAG':([3,5,6,7,8,9,],[-3,-2,8,9,-4,-5,]),'TEXT':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),'elementos':([0,3,4,],[2,5,7,]),'elemento':([0,3,4,],[3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> elementos','document',1,'p_document','parser_lexical.py',20),
  ('elementos -> elemento elementos','elementos',2,'p_elementos','parser_lexical.py',24),
  ('elementos -> elemento','elementos',1,'p_elementos','parser_lexical.py',25),
  ('elemento -> LTAG TEXT RTAG','elemento',3,'p_elemento','parser_lexical.py',29),
  ('elemento -> LTAG elementos RTAG','elemento',3,'p_elemento','parser_lexical.py',30),
]
